name: Deploy to ECS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Image Tag
      id: vars
      run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t app ./app

    - name: Tag Image
      run: |
        docker tag app:latest ${{ steps.login-ecr.outputs.registry }}/cloud-task-manager:${{ env.TAG }}

    - name: Push Image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/cloud-task-manager:${{ env.TAG }}

    #  REGISTER NEW TASK DEFINITION
    - name: Get current task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition cloud-task \
          --query taskDefinition > task-def.json
    
    - name: Install jq
      run: sudo apt-get install -y jq


    - name: Update image in task definition
      run: |
        jq --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/cloud-task-manager:${{ env.TAG }}" \
        '.containerDefinitions[0].image = $IMAGE' \
        task-def.json > new-task-def.json

    - name: Register new task definition
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json

    - name: Deploy new task definition
      run: |
        aws ecs update-service \
          --cluster cloud-cluster \
          --service cloud-service \
          --force-new-deployment
